### ISSUE TITLE
error on connection 

### ISSUE THREAD

**Issue by samuel1992** [joaopetreli/gobelisk#1]
Hello. Im trying to use your library but I have some problems.
First it shows me an error on action directory : 
`cannot find package "gobelisk/protocol/actions" in any of`
I think it was because the real directory is "action" instead, so I made a copy of "action" to "actions", problem solved.
Then, I tried to follow your example but I had this error : 
`./testGobelisk.go:11: cannot use &login (type *"gobelisk/protocol/actions".Login) as type `
`*"gobelisk/protocol/action".Login in argument to manager.Connect`

I really want to use it, if you could help-me, I will be grateful. Im brand new on Golang, then sorry me if I did some mistake.

**Comment by joaopetreli** [comment]
Hi!

I'm sorry, the import name in example "gobelisk/protocol/actions" was wrong. 
It should be "gobelisk/protocol/action" instead, not plural. I have already corrected it.

Thank you for your report!

**Comment by samuel1992** [comment]
Thank you!
